apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
  name: bookinfo-subscription
  namespace: bookinfo-project
spec:
  channel: bookinfo-source/bookinfo-ns-channel
  packageFilter:
    labelSelector:
      matchLabels:
        appname: bookinfo-demo
  placement:
    placementRef:
      name: bookinfo-rule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
---  
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-app
  namespace: bookinfo-project
spec:
  selector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - icam-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
